import "./globals.css";
import { Inconsolata } from "next/font/google";
import Navigation from "./components/nav";
import Footer from "./components/footer";

const inconsolata = Inconsolata({ subsets: ["latin"] , weight: "700" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inconsolata.className}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	);
}
